name: Currency Exchange UY
on:
  schedule:
    - cron: "0 15 */1 * *" # Every day at 15:00 UTC
  workflow_dispatch:

jobs:
  download-data:
    runs-on: ubuntu-latest
    steps:
      - name: Install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev pandoc -y
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Setup renv
        run: |
          install.packages('renv')
        shell: Rscript {0}
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install dependencies
        run: renv::restore()
        shell: Rscript {0}

      - name: Run Currency Exchange data downloader
        run: source("R/get_currency_exchange.R")
        shell: Rscript {0}

      - name: Run data processing
        run: source("R/format_currency_exchange.R")
        shell: Rscript {0}

      - name: Run dashboard builder
        run: source("R/dashboard_builder.R")
        shell: Rscript {0}

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "update data" && git push)
